code-chaser/project-leetcode

C++/addTwoNumbers.cpp
C++/partitionList.cpp
C++/rotateList.cpp
C++/swapNodesInPairs.cpp

- Add Two Numbers -  https://leetcode.com/problems/add-two-numbers/
- Swap Nodes in pairs -  https://leetcode.com/problems/swap-nodes-in-pairs/
- Rotate List -  https://leetcode.com/problems/rotate-list/
- Partition List -  https://leetcode.com/problems/partition-list/

add-solutions-1

---

C++/odd-even-linked-list.cpp
C++/reverse-linked-list.cpp
C++/reverse-nodes-in-k-group.cpp

- Reverse a Linked List - https://leetcode.com/problems/reverse-linked-list/
- Odd Even Linked List - https://leetcode.com/problems/odd-even-linked-list/
- Reverse Nodes in k-groups - https://leetcode.com/problems/reverse-nodes-in-k-group/

add-solutions-3

---

C++/merge-k-sorted-lists.cpp
C++/merge-two-sorted-lists.cpp
C++/sort-list.cpp

- Merge two Sorted Lists - https://leetcode.com/problems/merge-two-sorted-lists/
- Merge k Sorted Lists - https://leetcode.com/problems/merge-k-sorted-lists/
- Sort a List - https://leetcode.com/problems/sort-list/

add-solutions-4

---

src/cpp/trapping-rain-water.cpp

Problem: Trapping Rain Water (https://leetcode.com/problems/trapping-rain-water/)
My submission at leetcode: https://leetcode.com/submissions/detail/772574591/

Added leetcode solution for Trapping Rain Water

---

src/cpp/defanging-an-ip-address.cpp
src/cpp/path-sum-ii.cpp
src/cpp/path-sum.cpp
src/cpp/same-tree.cpp
src/cpp/symmetric-tree.cpp

added
same-tree 100
[->](https://leetcode.com/submissions/detail/803842022/)
symmetric tree 101
[->](https://leetcode.com/submissions/detail/803837894/
)
path sum 112
[->](https://leetcode.com/submissions/detail/809847376/)
path sum ii 113
[->](https://leetcode.com/submissions/detail/807215142/)
defanging an ip address 1108
[->](https://leetcode.com/submissions/detail/791753767/)

new commits

---

src/python/sum-of-two-integers.py

link : https://leetcode.com/problems/sum-of-two-integers/
for hacktoberfest

Added sum-of-two-integers py

---

src/cpp/best-time-to-buy-and-sell-stock-ii.cpp
src/cpp/best-time-to-buy-and-sell-stock.cpp

Problem 1:[Best Time to Buy and Sell Stock](https://leetcode.com/problems/best-time-to-buy-and-sell-stock/)
My submission: https://leetcode.com/submissions/detail/724908362/
Problem 2: [Best Time to Buy and Sell Stock II](https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/)
My submission: https://leetcode.com/submissions/detail/724912301/

Leetcode solutions for 2 parts of Best Time to Buy and Sell Stock

---

src/java/path-sum-ii.java
src/java/path-sum-iii.java
src/java/path-sum.java

[Question](https://leetcode.com/problems/path-sum/)
[Submission](https://leetcode.com/submissions/detail/434711704/)
[Question](https://leetcode.com/problems/path-sum-ii/)
[Submission](https://leetcode.com/submissions/detail/807289901/) 
[Question](https://leetcode.com/problems/path-sum-iii/)
[Submission](https://leetcode.com/submissions/detail/572580737/)

Leetcode Solution for binary tree - path sum i, ii and iii in java

---

src/java/meeting-rooms-iii.java
src/java/minimum-money-required-before-transactions.java
src/java/reverse_odd_levels_of_binary_tree.java

- [Meeting Rooms III](https://leetcode.com/problems/meeting-rooms-iii/description/)
- [Minimum Money Required Before Transactions](https://leetcode.com/problems/minimum-money-required-before-transactions/description/)
- [Reverse Odd Levels of Binary Tree](https://leetcode.com/problems/reverse-odd-levels-of-binary-tree/description/)
- [Meeting Rooms III](https://leetcode.com/problems/meeting-rooms-iii/submissions/790982792/)
- [Minimum Money Required Before Transactions](https://leetcode.com/problems/minimum-money-required-before-transactions/submissions/802093285/)
- [Reverse Odd Levels of Binary Tree](https://leetcode.com/problems/reverse-odd-levels-of-binary-tree/submissions/802550130/)

Added 2 Hard and 1 Medium Problems (for hacktoberfest)

---

src/cpp/edit-distance.cpp
src/cpp/find-median-from-data-stream.cpp

Problem: [Edit Distance](https://leetcode.com/problems/edit-distance/)
My Submission: https://leetcode.com/submissions/detail/660054525/
Problem: [Find Median from Data Stream](https://leetcode.com/problems/find-median-from-data-stream/)
My Submission: https://leetcode.com/submissions/detail/769549675/

Solutions for 2 hard questions Edit Distance and Median in Running Stream

---

src/cpp/maximum-subarray.cpp
src/cpp/validate-binary-search-tree.cpp

Problem Link: [Validate Binary Search Tree](https://leetcode.com/problems/validate-binary-search-tree/)
Submission: https://leetcode.com/submissions/detail/749154391/
Problem Link: [Factorial Trailing Zeroes](https://leetcode.com/problems/factorial-trailing-zeroes/)
Submission: https://leetcode.com/submissions/detail/772681233/
Problem Link: [Maximum Subarray](https://leetcode.com/problems/maximum-subarray/)
Submission: https://leetcode.com/submissions/detail/749167657/

LeetCode answers for 3 medium questions

---

132 pattern leetcode.txt
first and last position of element in sorted array.txt
merge two sorted list.txt

please add my file to your repository with label as hacktoberfest-accepted

Hactoberfest-2022

---

src/java/find-first-and-last-position-of-element-in-sorted-array.java
src/java/first_bad_version.java
src/java/search-in-rotated-sorted-array.java

- [First Bad Version](https://leetcode.com/problems/first-bad-version/description/)
- [Find First and Last Position of Element in Sorted Array](https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/description/)
- [Search in Rotated Sorted Array](https://leetcode.com/problems/search-in-rotated-sorted-array/description/)
- [First Bad Version](https://leetcode.com/problems/first-bad-version/submissions/634890233/)
- [Find First and Last Position of Element in Sorted Array](https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/submissions/635553424/)
- [Search in Rotated Sorted Array](https://leetcode.com/problems/search-in-rotated-sorted-array/submissions/635604256/)

Added 1 Easy and 2 Medium Problem (hacktoberfest)

---

src/cpp/lca_of_BT.cpp
src/cpp/number_of_islands.cpp
src/cpp/water_and_jug_problem.cpp

Submission Details attached: 
https://leetcode.com/submissions/detail/736863499/
https://leetcode.com/submissions/detail/727559231/
https://leetcode.com/submissions/detail/756921933/

Add solution for 3 LC Medium Problems

---

src/cpp/binary-tree-level-order-traversal-ii.cpp
src/cpp/binary-tree-level-order-traversal.cpp
src/cpp/course-schedule-iii.cpp
src/cpp/gas-station.cpp

[Question](https://leetcode.com/problems/binary-tree-level-order-traversal/)
[Submission](https://leetcode.com/submissions/detail/746124529/)
[Question](https://leetcode.com/problems/binary-tree-level-order-traversal-ii/)
[Submission](https://leetcode.com/submissions/detail/706141462/)
[Question](https://leetcode.com/problems/gas-station/)
[Submission](https://leetcode.com/submissions/detail/763086968/)
[Question](https://leetcode.com/problems/course-schedule-iii/)
[Submission](https://leetcode.com/submissions/detail/729083953/)

Leetcode Solution for 4 problems in CPP

---

src/cpp/power-of-four.cpp
src/cpp/power-of-three.cpp
src/cpp/power-of-two.cpp
src/cpp/reordered-power-of-2.cpp

Problem: [Power of Two](https://leetcode.com/problems/power-of-two/)
Submission: https://leetcode.com/submissions/detail/775344118/
Problem: [Power of Three](https://leetcode.com/problems/power-of-three/)
Submission: https://leetcode.com/submissions/detail/775358399/
Problem: [Power of Four](https://leetcode.com/problems/power-of-four/)
Submission: https://leetcode.com/submissions/detail/780119174/
Problem: [Reordered Power of 2](https://leetcode.com/problems/reordered-power-of-2/)
Submission: https://leetcode.com/submissions/detail/784163507/

Four Bit Manipulations Questions from LeetCode

---

src/cpp/buy-and-sell-stock-with-transaction-fee.cpp
src/cpp/decode-ways.cpp
src/cpp/number-of-dice-rolls-With-target-sum.cpp
src/cpp/unique-paths-2.cpp
src/cpp/unique-paths.cpp

Problems Solved
-> [Best Time to Buy and Sell Stock with Transaction Fee](https://leetcode.com/submissions/detail/753763392/)
-> [Unique Paths II](https://leetcode.com/submissions/detail/722221289/)
-> [Unique Paths](https://leetcode.com/submissions/detail/762177296/)
-> [Decode Ways](https://leetcode.com/submissions/detail/812935762/)
-> [Number of Dice Rolls With Target Sum](https://leetcode.com/submissions/detail/813414108/)

Add 5 DP Problems

---

src/java/remove-duplicates-from-sorted-list-ii.java
src/java/remove-duplicates-from-sorted-list.java
src/java/remove-nth-node-from-end-of-list.java
src/java/reverse-nodes-in-k-groups.java

[Question](https://leetcode.com/problems/reverse-nodes-in-k-group/)
[Submission](https://leetcode.com/submissions/detail/526062059/)
[Question](https://leetcode.com/problems/remove-nth-node-from-end-of-list/)
[Submission](https://leetcode.com/submissions/detail/810498154/)
[Question](https://leetcode.com/problems/remove-duplicates-from-sorted-list/)
[Submission](https://leetcode.com/submissions/detail/426116279/)
[Question](https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii/)
[Submission](https://leetcode.com/submissions/detail/656737500/)

Leetcode solutions for 4 problems of LinkedLists in Java

---

README.md
src/python/bitwise-AND-of-numbers-range.py
src/python/encrypt-and-decrypt-strings.py
src/python/keys-and-rooms.py
src/python/rotate-image.py
src/python/serialize-and-deserialize-binary-tree.py

Added Python3 solutions to the following problems:
1. [48. Rotate Image](https://leetcode.com/submissions/detail/558191451/)
2. [201. Bitwise AND of Numbers Range](https://leetcode.com/submissions/detail/813639391/)
3. [2227. Encrypt and Decrypt Strings](https://leetcode.com/submissions/detail/672795140/)
4. [841. Keys and Rooms](https://leetcode.com/submissions/detail/581346770/)
5. [297. Serialize and Deserialize Binary Tree](https://leetcode.com/submissions/detail/677535314/)
Also, updated the README.MD file with links to the problems and solutions.

Add new solutions

---

src/cpp/divide-two-integers.cpp
src/cpp/find-duplicate-subtrees.cpp
src/cpp/rotting-oranges.cpp

Solved the following three medium-level questions:
https://leetcode.com/problems/divide-two-integers/submissions/813659407/
https://leetcode.com/problems/rotting-oranges/submissions/813667505/
https://leetcode.com/problems/find-duplicate-subtrees/submissions/494435746/
Thankyou in advance !!

Leetcode Solutions 

---

src/cpp/backspace-string-compare.cpp
src/cpp/bitwise-and-of-numbers-range.cpp
src/cpp/construct-binary-search-tree-from-preorder-traversal.cpp
src/cpp/contiguous-array.cpp
src/cpp/diameter-of-binary-tree.cpp
src/cpp/group-anagrams.cpp
src/cpp/last-stone-weight.cpp
src/cpp/middle-of-the-linked-list.cpp
src/cpp/minimum-path-sum.cpp
src/cpp/search-in-rotated-sorted-array.cpp
src/cpp/subarray-sum-equals-k.cpp

@code-chaser I have tried to solve 11 leetcode problems. Please accept my PR.

Added 11 leetcode problem solutions

---

README.md
src/python/climbing-stairs.py
src/python/group-anagrams.py
src/python/powx-n.py
src/python/simplify-path.py
src/python/valid-sudoku.py

**Names of problems added:** 
- Valid Sudoku
- Group Anagrams
- Climbing Stairs
- Simplify Path
- Pow(x, n)
I am a Hacktoberfest Contributor :)

5 new Python problems added.

---

src/cpp/concatenation-of-array.cpp
src/cpp/count-good-triplets.cpp
src/cpp/count-number-of-pairs-with-absolute-difference-K.cpp
src/cpp/kids-with-the-greatest-number-of-candies.cpp
src/cpp/maximum-product-difference-between-two-pairs.cpp
src/cpp/number-of-good-pairs.cpp
src/cpp/richest-customer-wealth.cpp
src/cpp/running-sum-of-1d-array.cpp
src/cpp/shuffle-string.cpp
src/cpp/two-sum.cpp

[Concatenation of Array](https://leetcode.com/submissions/detail/814031632/)
[Count Good Triplets](https://leetcode.com/submissions/detail/814056641/)
[Count Number of Pairs With Absolute Difference K](https://leetcode.com/submissions/detail/814053994/)
[Kids With the Greatest Number of Candies](https://leetcode.com/submissions/detail/814037940/)
[Maximum Product Difference Between Two Pairs](https://leetcode.com/submissions/detail/814055226/)
[Number of Good Pairs](https://leetcode.com/submissions/detail/814033430/)
[Richest Customer Wealth](https://leetcode.com/submissions/detail/814048663/)
[Running Sum of 1d Array](https://leetcode.com/submissions/detail/814031981/)
[Shuffle String](https://leetcode.com/submissions/detail/814053699/)
[Two …

#47 Questions Solved in CPP

---

src/python/binary-tree-inorder-traversal.py
src/python/palindrome-number.py
src/python/roman-to-integer.py
src/python/two-sum.py

[Palindrome number](https://leetcode.com/submissions/detail/814298128/)
[Two Sum](https://leetcode.com/submissions/detail/814303122/)
Hacktoberfest 2022! :)

Added two python solutions

---

src/cpp/3sum.cpp
src/cpp/4sum.cpp
src/cpp/merge-sorted-array.cpp
src/cpp/minimum-time-to-make-rope-colorful.cpp

Problem: [3Sum](https://leetcode.com/problems/3sum/)
My Submission: https://leetcode.com/submissions/detail/718079495/
Problem: [4Sum](https://leetcode.com/problems/4sum/)
My Submission: https://leetcode.com/submissions/detail/744555109/
Problem: [Merge Sorted Array](https://leetcode.com/problems/merge-sorted-array/)
My Submission: https://leetcode.com/submissions/detail/604091597/
Problem: [Minimum Time to Make Rope Colorful](https://leetcode.com/problems/minimum-time-to-make-rope-colorful/)
My Submission: https://leetcode.com/submissions/detail/814074428/

3 sorting and one greedy question

---

src/cpp/maximum-binary.cpp
src/cpp/path-sum-iii.cpp
src/cpp/rotate-image.cpp
src/java/rotate-image.java
src/python/Count-Sub-Island.py
src/python/Execution-of-all-Suffix.py
src/python/gameoflife.py
src/python/minesweeper.py

-Four Codes in C++
-Three Codes in Python
-One Code in Java

Deleted Previous PR, created a New PR with 8 New Codes

---

binary-tree-cameras.cpp
cherry-pickup.cpp
maximum-sum-of-two-non-overlapping-subarrays.cpp

Below are submission details
https://leetcode.com/submissions/detail/804658055/
https://leetcode.com/submissions/detail/805204674/
https://leetcode.com/submissions/detail/804694582/

Added 3 leetcode problems in CPP

---

src/java/longest-substring-without-repeated-characters.java
src/java/palindrome-number.java
src/java/two-sum.java

Two solutions to leetcode Java: palindrome-number and longest-substring-without-repeating-characters

Added three solutions to leetcode Java

---

src/cpp/find-three-consecutive-integers-that-sum-to-a-given-number.cpp
src/cpp/integer-to-roman.cpp
src/cpp/reverse-integer.cpp
src/cpp/string-to-integer-atoi.cpp

Problem: [Reverse Integer](https://leetcode.com/problems/reverse-integer/)
Submission: https://leetcode.com/submissions/detail/667443404/
Problem: [Find Three Consecutive Integers That Sum to a Given Number](https://leetcode.com/problems/find-three-consecutive-integers-that-sum-to-a-given-number/)
Submission: https://leetcode.com/submissions/detail/801266514/
Problem: [String to Integer (atoi)](https://leetcode.com/problems/string-to-integer-atoi/)
Submission: https://leetcode.com/submissions/detail/786321327/
Problem: [Integer to Roman](https://leetcode.com/problems/integer-to-roman/)
Submission: https://leetcode.com/submissions/detail/718840625/

4 medium LeetCode questions

---

src/cpp/powx-n.cpp
src/cpp/rotate-image.cpp
src/cpp/search-a-2d-matrix.cpp
src/cpp/spiral-matrix.cpp

https://leetcode.com/problems/powx-n/
https://leetcode.com/problems/rotate-image/
https://leetcode.com/problems/search-a-2d-matrix/
https://leetcode.com/problems/spiral-matrix/

4 cpp problems added

---

src/cpp/first-bad-version.cpp
src/cpp/move-zeroes.cpp
src/cpp/number-complement.cpp
src/cpp/ransom-note.cpp
src/cpp/unique-number-of-occurrences.cpp

https://leetcode.com/problems/first-bad-version/
https://leetcode.com/problems/move-zeroes/
https://leetcode.com/problems/ransom-note/
https://leetcode.com/problems/number-complement/
https://leetcode.com/problems/unique-number-of-occurrences/

5 problems solved

---

src/cpp/container-with-most-water.cpp
src/cpp/find-the-index-of-the-first-occurrence-in-a-string.cpp
src/java/find-the-index-of-the-first-occurrence-in-a-string.java
src/python/find-the-index-of-the-first-occurrence-in-a-string.py
src/python/repeated-substring-pattern.py

Problem Statement: [Find the Index of the First Occurrence in a String](https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/)
Submission in cpp: https://leetcode.com/submissions/detail/815570389/
Submission in py: https://leetcode.com/submissions/detail/815571525/
Submission in java: https://leetcode.com/submissions/detail/759951386/
Problem Statement: [Repeated Substring Pattern](https://leetcode.com/problems/repeated-substring-pattern/)
Submission: https://leetcode.com/submissions/detail/815574165/
Problem Statement: [Container With Most Water](https://leetcode.com/problems/container-with-most-water/)
Submission: https://leetcode.com/submissions/detail/772556970/

5 leetcode solutions

---

src/cpp/maximum-matching-of-players-with-trainers.cpp
src/cpp/maximum-points-you-can-obtain-from-cards.cpp
src/cpp/palindrome-partitioning.cpp

Following are my submissions
https://leetcode.com/submissions/detail/802239929/
https://leetcode.com/contest/biweekly-contest-87/submissions/detail/802043244/
https://leetcode.com/submissions/detail/803056172/

Added 3 programs in CPP leetcode

---

src/java/best-time-to-buy-and-sell-stock-with-transaction-fee.java
src/java/palindrome-partitioning-ii.java
src/java/palindromic-substrings.java

- https://leetcode.com/problems/palindrome-partitioning-ii/description/
- https://leetcode.com/problems/palindromic-substrings/description/
- https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee/description/
- https://leetcode.com/problems/palindrome-partitioning-ii/submissions/737412173/
- https://leetcode.com/problems/palindromic-substrings/submissions/620740483/
- https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee/submissions/664871512/

Added 1 Hard and 2 medium questions (hacktoberfect)

---

src/cpp/count-hills-and-valleys-in-an-array.cpp
src/cpp/count-primes.cpp
src/cpp/find-pivot-index.cpp
src/cpp/rotate-array.cpp
src/cpp/search-a-2d-matrix-ii.cpp

https://leetcode.com/problems/count-hills-and-valleys-in-an-array/
https://leetcode.com/problems/find-pivot-index/
https://leetcode.com/problems/count-primes/
https://leetcode.com/problems/rotate-array/
https://leetcode.com/problems/search-a-2d-matrix-ii/

new contribution

---

README.md
src/python/find-the-original-array-of-prefix-xor.py
src/python/the-employee-that-worked-on-the-longest-task.py
src/python/using-a-robot-to-print-the-lexicographically-smallest-string.py

- [2432. The Employee That Worked on the Longest Task](https://leetcode.com/submissions/detail/818439757/)
- [2433. Find The Original Array of Prefix Xor](https://leetcode.com/submissions/detail/818442872/)
- [2434. Using a Robot to Print the Lexicographically Smallest String](https://leetcode.com/submissions/detail/818446218/)

Add 3 Python solutions

---

src/cpp/binary-search-tree-iterator.cpp
src/cpp/convert-sorted-array-to-binary-search-tree.cpp
src/cpp/recover-binary-search-tree.cpp

Submission Links -
recover-binary-search-tree - https://leetcode.com/submissions/detail/775984425/
convert-sorted-array-to-binary-search-tree - https://leetcode.com/submissions/detail/753184296/
binary-search-tree-iterator - https://leetcode.com/submissions/detail/758084009/

Added 3 leetcode problem solutions in C++

---

src/cpp/maximal-rectangle.cpp
src/cpp/regular-expression-matching.cpp
src/cpp/scramble-string.cpp

https://leetcode.com/problems/regular-expression-matching/submissions/438564711/
https://leetcode.com/problems/maximal-rectangle/submissions/469481781/
https://leetcode.com/problems/scramble-string/submissions/471324466/
Please accept the PR.
Thankyou !!

Leetcode Questions Solved

---

src/cpp/merge-intervals.cpp
src/cpp/set-matrix-zeroes.cpp
src/cpp/sort-colors.cpp

Problem links:
1) merge-intervals - https://leetcode.com/problems/merge-intervals/
2) sort-colors - https://leetcode.com/problems/sort-colors/
3) set-matrix-zeroes - https://leetcode.com/problems/set-matrix-zeroes/

Added 3 optimized leetcode solutions in C++

---

README.md
src/cpp/word-break-ii.cpp

Added solution for word break II on leetcode in C++.

[C++] Added Word Break II

---

src/cpp/pacific-atlantic-water-flow.cpp

Added solution for Pacific atlantic water flow problem from leetcode.
https://leetcode.com/problems/pacific-atlantic-water-flow/

[C++] Added pacific atlantic water flow

---

src/cpp/best-time-to-buy-and-sell-stock-iv.cpp

https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/
https://www.interviewbit.com/problems/best-time-to-buy-and-sell-stock-atmost-b-times/

[C++] Buy and sell stocks with at-most K transactions

---

CODE_OF_CONDUCT.md

- created `CODE_OF_CONDUCT.md`
- please review

[DOCUMENTATION]
